# Character-Level LSTM in PyTorch

In this notebook, I'll construct a character-level LSTM with PyTorch. The network will train character by character on some text, then generate new text character by character. As an example, I will train on Anna Karenina. **This model will be able to generate new text based on the text from the book!**

This network is based off of Andrej Karpathy's [post on RNNs](http://karpathy.github.io/2015/05/21/rnn-effectiveness/) and [implementation in Torch](https://github.com/karpathy/char-rnn). Below is the general architecture of the character-wise RNN.

<img src="assets/charseq.jpeg" width="500">

First let's load in our required resources for data loading and model creation.

In [1]:
import numpy as np
import torch
from torch import nn
import torch.nn.functional as F

## Load in Data

Then, we'll load the Anna Karenina text file and convert it into integers for our network to use. 

In [2]:
# open text file and read in data as `text`
with open('data/anna.txt', 'r') as f:
    text = f.read()

Let's check out the first 100 characters, make sure everything is peachy. According to the [American Book Review](http://americanbookreview.org/100bestlines.asp), this is the 6th best first line of a book ever.

In [3]:
text[:100]

'Chapter 1\n\n\nHappy families are all alike; every unhappy family is unhappy in its own\nway.\n\nEverythin'

### Tokenization

In the cells, below, I'm creating a couple **dictionaries** to convert the characters to and from integers. Encoding the characters as integers makes it easier to use as input in the network.

In [4]:
# encode the text and map each character to an integer and vice versa

# we create two dictionaries:
# 1. int2char, which maps integers to characters
# 2. char2int, which maps characters to unique integers
chars = tuple(set(text))
int2char = dict(enumerate(chars))
char2int = {ch: ii for ii, ch in int2char.items()}

# encode the text
encoded = np.array([char2int[ch] for ch in text])

And we can see those same characters from above, encoded as integers.

In [5]:
encoded[:100]

array([24, 77,  6, 80, 34, 47, 42, 63, 33, 25, 25, 25, 67,  6, 80, 80, 50,
       63, 56,  6, 38, 59, 21, 59, 47, 69, 63,  6, 42, 47, 63,  6, 21, 21,
       63,  6, 21, 59,  4, 47, 35, 63, 47, 28, 47, 42, 50, 63, 16, 22, 77,
        6, 80, 80, 50, 63, 56,  6, 38, 59, 21, 50, 63, 59, 69, 63, 16, 22,
       77,  6, 80, 80, 50, 63, 59, 22, 63, 59, 34, 69, 63, 37, 43, 22, 25,
       43,  6, 50, 52, 25, 25, 82, 28, 47, 42, 50, 34, 77, 59, 22])

## Pre-processing the data

As you can see in our char-RNN image above, our LSTM expects an input that is **one-hot encoded** meaning that each character is converted into an integer (via our created dictionary) and *then* converted into a column vector where only it's corresponding integer index will have the value of 1 and the rest of the vector will be filled with 0's. Since we're one-hot encoding the data, let's make a function to do that!


In [6]:
def one_hot_encode(arr, n_labels):
    
    # Initialize the the encoded array
    one_hot = np.zeros((arr.size, n_labels), dtype=np.float32)
    
    # Fill the appropriate elements with ones
    one_hot[np.arange(one_hot.shape[0]), arr.flatten()] = 1.
    
    # Finally reshape it to get back to the original array
    one_hot = one_hot.reshape((*arr.shape, n_labels))
    
    return one_hot

In [7]:
# check that the function works as expected
test_seq = np.array([[3, 5, 1]])
one_hot = one_hot_encode(test_seq, 8)

print(one_hot)

[[[0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]]]


## Making training mini-batches


To train on this data, we also want to create mini-batches for training. Remember that we want our batches to be multiple sequences of some desired number of sequence steps. Considering a simple example, our batches would look like this:

<img src="assets/sequence_batching@1x.png" width=500px>


<br>

In this example, we'll take the encoded characters (passed in as the `arr` parameter) and split them into multiple sequences, given by `batch_size`. Each of our sequences will be `seq_length` long.

### Creating Batches

**1. The first thing we need to do is discard some of the text so we only have completely full mini-batches. **

Each batch contains $N \times M$ characters, where $N$ is the batch size (the number of sequences in a batch) and $M$ is the seq_length or number of time steps in a sequence. Then, to get the total number of batches, $K$, that we can make from the array `arr`, you divide the length of `arr` by the number of characters per batch. Once you know the number of batches, you can get the total number of characters to keep from `arr`, $N * M * K$.

**2. After that, we need to split `arr` into $N$ batches. ** 

You can do this using `arr.reshape(size)` where `size` is a tuple containing the dimensions sizes of the reshaped array. We know we want $N$ sequences in a batch, so let's make that the size of the first dimension. For the second dimension, you can use `-1` as a placeholder in the size, it'll fill up the array with the appropriate data for you. After this, you should have an array that is $N \times (M * K)$.

**3. Now that we have this array, we can iterate through it to get our mini-batches. **

The idea is each batch is a $N \times M$ window on the $N \times (M * K)$ array. For each subsequent batch, the window moves over by `seq_length`. We also want to create both the input and target arrays. Remember that the targets are just the inputs shifted over by one character. The way I like to do this window is use `range` to take steps of size `n_steps` from $0$ to `arr.shape[1]`, the total number of tokens in each sequence. That way, the integers you get from `range` always point to the start of a batch, and each window is `seq_length` wide.

> **TODO:** Write the code for creating batches in the function below. The exercises in this notebook _will not be easy_. I've provided a notebook with solutions alongside this notebook. If you get stuck, checkout the solutions. The most important thing is that you don't copy and paste the code into here, **type out the solution code yourself.**

In [99]:
def get_batches(arr, batch_size, seq_length):
    '''Create a generator that returns batches of size
       batch_size x seq_length from arr.
       
       Arguments
       ---------
       arr: Array you want to make batches from
       batch_size: Batch size, the number of sequences per batch
       seq_length: Number of encoded chars in a sequence
    '''
    
    ## TODO: Get the number of batches we can make
    n_batches = int((len(arr)-batch_size)/(batch_size*seq_length))
    #print(f'n_batches {n_batches}')
    
    ## TODO: Keep only enough characters to make full batches
    arr = arr[:batch_size*seq_length*n_batches+batch_size]
    
    ## TODO: Reshape into batch_size rows
    arr = np.reshape(arr, (batch_size, -1))
    #print(f'arr.shape {arr.shape}')
    
    ## TODO: Iterate over the batches using a window of size seq_length
    for n in range(0, arr.shape[1]-1, seq_length):
        # The features
        x = arr[:, n:n+seq_length]
        # The targets, shifted by one
        y = arr[:, n+1:n+seq_length+1]
        yield x, y

### Test Your Implementation

Now I'll make some data sets and we can check out what's going on as we batch data. Here, as an example, I'm going to use a batch size of 8 and 50 sequence steps.

In [100]:
batches = get_batches(encoded, 8, 50)
x, y = next(batches)

In [101]:
# printing out the first 10 items in a sequence
print('x\n', x[:10, :10])
print('\ny\n', y[:10, :10])

x
 [[24 77  6 80 34 47 42 63 33 25]
 [37 22 63 34 77  6 34 63  6 34]
 [71 63 37 42 63  6 63 56 37 47]
 [77 47 63 26 77 59 47 56 63 34]
 [63 77 47 42 63 34 47  6 42 75]
 [37 22 63  6 22 71 63  6 22  6]
 [77  6 71 63 69  6 59 71 63 34]
 [50 52 63 15 74 16 34 63 27 34]]

y
 [[77  6 80 34 47 42 63 33 25 25]
 [22 63 34 77  6 34 63  6 34 34]
 [63 37 42 63  6 63 56 37 47 51]
 [47 63 26 77 59 47 56 63 34 77]
 [77 47 42 63 34 47  6 42 75 69]
 [22 63  6 22 71 63  6 22  6 21]
 [ 6 71 63 69  6 59 71 63 34 77]
 [52 63 15 74 16 34 63 27 34 77]]


If you implemented `get_batches` correctly, the above output should look something like 
```
x
 [[25  8 60 11 45 27 28 73  1  2]
 [17  7 20 73 45  8 60 45 73 60]
 [27 20 80 73  7 28 73 60 73 65]
 [17 73 45  8 27 73 66  8 46 27]
 [73 17 60 12 73  8 27 28 73 45]
 [66 64 17 17 46  7 20 73 60 20]
 [73 76 20 20 60 73  8 60 80 73]
 [47 35 43  7 20 17 24 50 37 73]]

y
 [[ 8 60 11 45 27 28 73  1  2  2]
 [ 7 20 73 45  8 60 45 73 60 45]
 [20 80 73  7 28 73 60 73 65  7]
 [73 45  8 27 73 66  8 46 27 65]
 [17 60 12 73  8 27 28 73 45 27]
 [64 17 17 46  7 20 73 60 20 80]
 [76 20 20 60 73  8 60 80 73 17]
 [35 43  7 20 17 24 50 37 73 36]]
 ```
 although the exact numbers may be different. Check to make sure the data is shifted over one step for `y`.

---
## Defining the network with PyTorch

Below is where you'll define the network.

<img src="assets/charRNN.png" width=500px>

Next, you'll use PyTorch to define the architecture of the network. We start by defining the layers and operations we want. Then, define a method for the forward pass. You've also been given a method for predicting characters.

### Model Structure

In `__init__` the suggested structure is as follows:
* Create and store the necessary dictionaries (this has been done for you)
* Define an LSTM layer that takes as params: an input size (the number of characters), a hidden layer size `n_hidden`, a number of layers `n_layers`, a dropout probability `drop_prob`, and a batch_first boolean (True, since we are batching)
* Define a dropout layer with `drop_prob`
* Define a fully-connected layer with params: input size `n_hidden` and output size (the number of characters)
* Finally, initialize the weights (again, this has been given)

Note that some parameters have been named and given in the `__init__` function, and we use them and store them by doing something like `self.drop_prob = drop_prob`.

---
### LSTM Inputs/Outputs

You can create a basic [LSTM layer](https://pytorch.org/docs/stable/nn.html#lstm) as follows

```python
self.lstm = nn.LSTM(input_size, n_hidden, n_layers, 
                            dropout=drop_prob, batch_first=True)
```

where `input_size` is the number of characters this cell expects to see as sequential input, and `n_hidden` is the number of units in the hidden layers in the cell. And we can add dropout by adding a dropout parameter with a specified probability; this will automatically add dropout to the inputs or outputs. Finally, in the `forward` function, we can stack up the LSTM cells into layers using `.view`. With this, you pass in a list of cells and it will send the output of one cell into the next cell.

We also need to create an initial hidden state of all zeros. This is done like so

```python
self.init_hidden()
```

In [102]:
# check if GPU is available
train_on_gpu = torch.cuda.is_available()
if(train_on_gpu):
    print('Training on GPU!')
else: 
    print('No GPU available, training on CPU; consider making n_epochs very small.')

No GPU available, training on CPU; consider making n_epochs very small.


In [103]:
class CharRNN(nn.Module):
    
    def __init__(self, tokens, n_hidden=256, n_layers=2,
                               drop_prob=0.5, lr=0.001):
        super().__init__()
        self.drop_prob = drop_prob
        self.n_layers = n_layers
        self.n_hidden = n_hidden
        self.lr = lr
        
        # creating character dictionaries
        self.chars = tokens
        self.int2char = dict(enumerate(self.chars))
        self.char2int = {ch: ii for ii, ch in self.int2char.items()}
        
        ## TODO: define the layers of the model
        self.lstm = nn.LSTM(len(self.chars), self.n_hidden, self.n_layers, 
                            dropout=self.drop_prob, batch_first=True)
        self.fc = nn.Linear(n_hidden, len(self.chars))
      
    
    def forward(self, x, hidden):
        ''' Forward pass through the network. 
            These inputs are x, and the hidden/cell state `hidden`. '''
                
        ## TODO: Get the outputs and the new hidden state from the lstm
        out, hidden = self.lstm(x, hidden)
        #print(f'out.shape {out.shape}')
        out = out.contiguous().view(-1, self.n_hidden)
        out = self.fc(out)
        
        # return the final output and the hidden state
        return out, hidden
    
    
    def init_hidden(self, batch_size):
        ''' Initializes hidden state '''
        # Create two new tensors with sizes n_layers x batch_size x n_hidden,
        # initialized to zero, for hidden state and cell state of LSTM
        weight = next(self.parameters()).data
        
        if (train_on_gpu):
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda(),
                  weight.new(self.n_layers, batch_size, self.n_hidden).zero_().cuda())
        else:
            hidden = (weight.new(self.n_layers, batch_size, self.n_hidden).zero_(),
                      weight.new(self.n_layers, batch_size, self.n_hidden).zero_())
        
        return hidden
        

## Time to train

The train function gives us the ability to set the number of epochs, the learning rate, and other parameters.

Below we're using an Adam optimizer and cross entropy loss since we are looking at character class scores as output. We calculate the loss and perform backpropagation, as usual!

A couple of details about training: 
>* Within the batch loop, we detach the hidden state from its history; this time setting it equal to a new *tuple* variable because an LSTM has a hidden state that is a tuple of the hidden and cell states.
* We use [`clip_grad_norm_`](https://pytorch.org/docs/stable/_modules/torch/nn/utils/clip_grad.html) to help prevent exploding gradients.

In [104]:
def train(net, data, epochs=10, batch_size=10, seq_length=50, lr=0.001, clip=5, val_frac=0.1, print_every=10):
    ''' Training a network 
    
        Arguments
        ---------
        
        net: CharRNN network
        data: text data to train the network
        epochs: Number of epochs to train
        batch_size: Number of mini-sequences per mini-batch, aka batch size
        seq_length: Number of character steps per mini-batch
        lr: learning rate
        clip: gradient clipping
        val_frac: Fraction of data to hold out for validation
        print_every: Number of steps for printing training and validation loss
    
    '''
    net.train()
    
    opt = torch.optim.Adam(net.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()
    
    # create training and validation data
    val_idx = int(len(data)*(1-val_frac))
    data, val_data = data[:val_idx], data[val_idx:]
    
    if(train_on_gpu):
        net.cuda()
    
    counter = 0
    n_chars = len(net.chars)
    for e in range(epochs):
        # initialize hidden state
        h = net.init_hidden(batch_size)
        
        for x, y in get_batches(data, batch_size, seq_length):
            counter += 1
            
            # One-hot encode our data and make them Torch tensors
            x = one_hot_encode(x, n_chars)
            inputs, targets = torch.from_numpy(x), torch.from_numpy(y)
            
            if(train_on_gpu):
                inputs, targets = inputs.cuda(), targets.cuda()

            # Creating new variables for the hidden state, otherwise
            # we'd backprop through the entire training history
            h = tuple([each.data for each in h])
            #print(f'h {h}')

            # zero accumulated gradients
            net.zero_grad()
            
            # get the output from the model
            output, h = net(inputs, h)
            
            # calculate the loss and perform backprop
            loss = criterion(output, targets.reshape(batch_size*seq_length).long())
            loss.backward()
            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs / LSTMs.
            nn.utils.clip_grad_norm_(net.parameters(), clip)
            opt.step()
            
            # loss stats
            if counter % print_every == 0:
                # Get validation loss
                val_h = net.init_hidden(batch_size)
                val_losses = []
                net.eval()
                for x, y in get_batches(val_data, batch_size, seq_length):
                    # One-hot encode our data and make them Torch tensors
                    x = one_hot_encode(x, n_chars)
                    x, y = torch.from_numpy(x), torch.from_numpy(y)
                    
                    # Creating new variables for the hidden state, otherwise
                    # we'd backprop through the entire training history
                    val_h = tuple([each.data for each in val_h])
                    
                    inputs, targets = x, y
                    if(train_on_gpu):
                        inputs, targets = inputs.cuda(), targets.cuda()

                    output, val_h = net(inputs, val_h)
                    val_loss = criterion(output, targets.reshape(batch_size*seq_length).long())
                
                    val_losses.append(val_loss.item())
                
                net.train() # reset to train mode after iterationg through validation data
                
                print("Epoch: {}/{}...".format(e+1, epochs),
                      "Step: {}...".format(counter),
                      "Loss: {:.4f}...".format(loss.item()),
                      "Val Loss: {:.4f}".format(np.mean(val_losses)))

## Instantiating the model

Now we can actually train the network. First we'll create the network itself, with some given hyperparameters. Then, define the mini-batches sizes, and start training!

In [105]:
## TODO: set your model hyperparameters
# define and print the net
n_hidden=256
n_layers=2

net = CharRNN(chars, n_hidden, n_layers)
print(net)

CharRNN(
  (lstm): LSTM(83, 256, num_layers=2, batch_first=True, dropout=0.5)
  (fc): Linear(in_features=256, out_features=83, bias=True)
)


### Set your training hyperparameters!

In [106]:
batch_size = 8
seq_length = 50
n_epochs =  10# start small if you are just testing initial behavior

# train the model
train(net, encoded, epochs=n_epochs, batch_size=batch_size, seq_length=seq_length, lr=0.001, print_every=10)

Epoch: 1/10... Step: 10... Loss: 3.2115... Val Loss: 3.2353
Epoch: 1/10... Step: 20... Loss: 3.0746... Val Loss: 3.1561
Epoch: 1/10... Step: 30... Loss: 3.1672... Val Loss: 3.1510
Epoch: 1/10... Step: 40... Loss: 3.0845... Val Loss: 3.1392
Epoch: 1/10... Step: 50... Loss: 3.0024... Val Loss: 3.1352
Epoch: 1/10... Step: 60... Loss: 3.0387... Val Loss: 3.1469
Epoch: 1/10... Step: 70... Loss: 3.0026... Val Loss: 3.1392
Epoch: 1/10... Step: 80... Loss: 3.0110... Val Loss: 3.1388
Epoch: 1/10... Step: 90... Loss: 3.0820... Val Loss: 3.1413
Epoch: 1/10... Step: 100... Loss: 3.0795... Val Loss: 3.1372
Epoch: 1/10... Step: 110... Loss: 3.1350... Val Loss: 3.1363
Epoch: 1/10... Step: 120... Loss: 3.0707... Val Loss: 3.1401
Epoch: 1/10... Step: 130... Loss: 3.0395... Val Loss: 3.1334
Epoch: 1/10... Step: 140... Loss: 3.0373... Val Loss: 3.1306
Epoch: 1/10... Step: 150... Loss: 3.2028... Val Loss: 3.1419
Epoch: 1/10... Step: 160... Loss: 3.0541... Val Loss: 3.1357
Epoch: 1/10... Step: 170... Loss:

Epoch: 1/10... Step: 1350... Loss: 2.1219... Val Loss: 2.1502
Epoch: 1/10... Step: 1360... Loss: 2.1276... Val Loss: 2.1416
Epoch: 1/10... Step: 1370... Loss: 2.0250... Val Loss: 2.1403
Epoch: 1/10... Step: 1380... Loss: 2.0246... Val Loss: 2.1449
Epoch: 1/10... Step: 1390... Loss: 2.0833... Val Loss: 2.1466
Epoch: 1/10... Step: 1400... Loss: 1.9888... Val Loss: 2.1400
Epoch: 1/10... Step: 1410... Loss: 1.9485... Val Loss: 2.1331
Epoch: 1/10... Step: 1420... Loss: 2.0415... Val Loss: 2.1350
Epoch: 1/10... Step: 1430... Loss: 2.0406... Val Loss: 2.1271
Epoch: 1/10... Step: 1440... Loss: 2.1278... Val Loss: 2.1309
Epoch: 1/10... Step: 1450... Loss: 2.1336... Val Loss: 2.1296
Epoch: 1/10... Step: 1460... Loss: 2.0674... Val Loss: 2.1207
Epoch: 1/10... Step: 1470... Loss: 2.0174... Val Loss: 2.1189
Epoch: 1/10... Step: 1480... Loss: 2.0692... Val Loss: 2.1201
Epoch: 1/10... Step: 1490... Loss: 2.1422... Val Loss: 2.1113
Epoch: 1/10... Step: 1500... Loss: 2.0406... Val Loss: 2.1088
Epoch: 1

Epoch: 1/10... Step: 2680... Loss: 1.8295... Val Loss: 1.8827
Epoch: 1/10... Step: 2690... Loss: 1.8175... Val Loss: 1.8769
Epoch: 1/10... Step: 2700... Loss: 1.8826... Val Loss: 1.8797
Epoch: 1/10... Step: 2710... Loss: 1.8503... Val Loss: 1.8824
Epoch: 1/10... Step: 2720... Loss: 1.7406... Val Loss: 1.8756
Epoch: 1/10... Step: 2730... Loss: 1.7540... Val Loss: 1.8747
Epoch: 1/10... Step: 2740... Loss: 1.7194... Val Loss: 1.8714
Epoch: 1/10... Step: 2750... Loss: 1.8807... Val Loss: 1.8645
Epoch: 1/10... Step: 2760... Loss: 1.7798... Val Loss: 1.8629
Epoch: 1/10... Step: 2770... Loss: 1.9031... Val Loss: 1.8592
Epoch: 1/10... Step: 2780... Loss: 1.8553... Val Loss: 1.8631
Epoch: 1/10... Step: 2790... Loss: 1.8060... Val Loss: 1.8590
Epoch: 1/10... Step: 2800... Loss: 1.9003... Val Loss: 1.8704
Epoch: 1/10... Step: 2810... Loss: 1.8152... Val Loss: 1.8661
Epoch: 1/10... Step: 2820... Loss: 1.8597... Val Loss: 1.8560
Epoch: 1/10... Step: 2830... Loss: 1.8880... Val Loss: 1.8543
Epoch: 1

Epoch: 1/10... Step: 4010... Loss: 1.5786... Val Loss: 1.7321
Epoch: 1/10... Step: 4020... Loss: 1.4967... Val Loss: 1.7355
Epoch: 1/10... Step: 4030... Loss: 1.7787... Val Loss: 1.7311
Epoch: 1/10... Step: 4040... Loss: 1.6537... Val Loss: 1.7249
Epoch: 1/10... Step: 4050... Loss: 1.6332... Val Loss: 1.7290
Epoch: 1/10... Step: 4060... Loss: 1.5278... Val Loss: 1.7281
Epoch: 1/10... Step: 4070... Loss: 1.6049... Val Loss: 1.7203
Epoch: 1/10... Step: 4080... Loss: 1.6071... Val Loss: 1.7230
Epoch: 1/10... Step: 4090... Loss: 1.4837... Val Loss: 1.7273
Epoch: 1/10... Step: 4100... Loss: 1.4119... Val Loss: 1.7244
Epoch: 1/10... Step: 4110... Loss: 1.4836... Val Loss: 1.7377
Epoch: 1/10... Step: 4120... Loss: 1.6410... Val Loss: 1.7288
Epoch: 1/10... Step: 4130... Loss: 1.5633... Val Loss: 1.7235
Epoch: 1/10... Step: 4140... Loss: 1.8053... Val Loss: 1.7246
Epoch: 1/10... Step: 4150... Loss: 1.6308... Val Loss: 1.7211
Epoch: 1/10... Step: 4160... Loss: 1.5843... Val Loss: 1.7243
Epoch: 1

Epoch: 2/10... Step: 5340... Loss: 1.6054... Val Loss: 1.6395
Epoch: 2/10... Step: 5350... Loss: 1.4148... Val Loss: 1.6413
Epoch: 2/10... Step: 5360... Loss: 1.6589... Val Loss: 1.6420
Epoch: 2/10... Step: 5370... Loss: 1.6238... Val Loss: 1.6382
Epoch: 2/10... Step: 5380... Loss: 1.5602... Val Loss: 1.6377
Epoch: 2/10... Step: 5390... Loss: 1.4491... Val Loss: 1.6424
Epoch: 2/10... Step: 5400... Loss: 1.5561... Val Loss: 1.6344
Epoch: 2/10... Step: 5410... Loss: 1.5347... Val Loss: 1.6353
Epoch: 2/10... Step: 5420... Loss: 1.4264... Val Loss: 1.6351
Epoch: 2/10... Step: 5430... Loss: 1.4275... Val Loss: 1.6313
Epoch: 2/10... Step: 5440... Loss: 1.3634... Val Loss: 1.6373
Epoch: 2/10... Step: 5450... Loss: 1.5465... Val Loss: 1.6342
Epoch: 2/10... Step: 5460... Loss: 1.5903... Val Loss: 1.6301
Epoch: 2/10... Step: 5470... Loss: 1.4081... Val Loss: 1.6330
Epoch: 2/10... Step: 5480... Loss: 1.3956... Val Loss: 1.6368
Epoch: 2/10... Step: 5490... Loss: 1.5243... Val Loss: 1.6343
Epoch: 2

Epoch: 2/10... Step: 6670... Loss: 1.4951... Val Loss: 1.5837
Epoch: 2/10... Step: 6680... Loss: 1.4644... Val Loss: 1.5855
Epoch: 2/10... Step: 6690... Loss: 1.3984... Val Loss: 1.5875
Epoch: 2/10... Step: 6700... Loss: 1.5422... Val Loss: 1.5897
Epoch: 2/10... Step: 6710... Loss: 1.3936... Val Loss: 1.5865
Epoch: 2/10... Step: 6720... Loss: 1.5745... Val Loss: 1.5918
Epoch: 2/10... Step: 6730... Loss: 1.6136... Val Loss: 1.5832
Epoch: 2/10... Step: 6740... Loss: 1.3299... Val Loss: 1.5816
Epoch: 2/10... Step: 6750... Loss: 1.4388... Val Loss: 1.5856
Epoch: 2/10... Step: 6760... Loss: 1.6097... Val Loss: 1.5778
Epoch: 2/10... Step: 6770... Loss: 1.3160... Val Loss: 1.5781
Epoch: 2/10... Step: 6780... Loss: 1.4965... Val Loss: 1.5800
Epoch: 2/10... Step: 6790... Loss: 1.5168... Val Loss: 1.5810
Epoch: 2/10... Step: 6800... Loss: 1.4970... Val Loss: 1.5831
Epoch: 2/10... Step: 6810... Loss: 1.4169... Val Loss: 1.5791
Epoch: 2/10... Step: 6820... Loss: 1.4925... Val Loss: 1.5812
Epoch: 2

Epoch: 2/10... Step: 8000... Loss: 1.3210... Val Loss: 1.5337
Epoch: 2/10... Step: 8010... Loss: 1.7008... Val Loss: 1.5357
Epoch: 2/10... Step: 8020... Loss: 1.2989... Val Loss: 1.5359
Epoch: 2/10... Step: 8030... Loss: 1.4637... Val Loss: 1.5371
Epoch: 2/10... Step: 8040... Loss: 1.4233... Val Loss: 1.5385
Epoch: 2/10... Step: 8050... Loss: 1.2633... Val Loss: 1.5368
Epoch: 2/10... Step: 8060... Loss: 1.7218... Val Loss: 1.5354
Epoch: 2/10... Step: 8070... Loss: 1.4302... Val Loss: 1.5339
Epoch: 2/10... Step: 8080... Loss: 1.4816... Val Loss: 1.5397
Epoch: 2/10... Step: 8090... Loss: 1.5637... Val Loss: 1.5367
Epoch: 2/10... Step: 8100... Loss: 1.6625... Val Loss: 1.5398
Epoch: 2/10... Step: 8110... Loss: 1.4928... Val Loss: 1.5412
Epoch: 2/10... Step: 8120... Loss: 1.4662... Val Loss: 1.5354
Epoch: 2/10... Step: 8130... Loss: 1.3362... Val Loss: 1.5409
Epoch: 2/10... Step: 8140... Loss: 1.4448... Val Loss: 1.5417
Epoch: 2/10... Step: 8150... Loss: 1.4404... Val Loss: 1.5370
Epoch: 2

Epoch: 3/10... Step: 9330... Loss: 1.3764... Val Loss: 1.5134
Epoch: 3/10... Step: 9340... Loss: 1.3501... Val Loss: 1.5159
Epoch: 3/10... Step: 9350... Loss: 1.4331... Val Loss: 1.5156
Epoch: 3/10... Step: 9360... Loss: 1.4707... Val Loss: 1.5174
Epoch: 3/10... Step: 9370... Loss: 1.4476... Val Loss: 1.5119
Epoch: 3/10... Step: 9380... Loss: 1.3072... Val Loss: 1.5103
Epoch: 3/10... Step: 9390... Loss: 1.5478... Val Loss: 1.5064
Epoch: 3/10... Step: 9400... Loss: 1.3879... Val Loss: 1.5077
Epoch: 3/10... Step: 9410... Loss: 1.3198... Val Loss: 1.5088
Epoch: 3/10... Step: 9420... Loss: 1.4047... Val Loss: 1.5049
Epoch: 3/10... Step: 9430... Loss: 1.4757... Val Loss: 1.5079
Epoch: 3/10... Step: 9440... Loss: 1.5363... Val Loss: 1.5142
Epoch: 3/10... Step: 9450... Loss: 1.4239... Val Loss: 1.5108
Epoch: 3/10... Step: 9460... Loss: 1.2906... Val Loss: 1.5130
Epoch: 3/10... Step: 9470... Loss: 1.3055... Val Loss: 1.5053
Epoch: 3/10... Step: 9480... Loss: 1.3973... Val Loss: 1.5128
Epoch: 3

Epoch: 3/10... Step: 10650... Loss: 1.3795... Val Loss: 1.4946
Epoch: 3/10... Step: 10660... Loss: 1.3932... Val Loss: 1.5019
Epoch: 3/10... Step: 10670... Loss: 1.2563... Val Loss: 1.4989
Epoch: 3/10... Step: 10680... Loss: 1.3667... Val Loss: 1.4953
Epoch: 3/10... Step: 10690... Loss: 1.4387... Val Loss: 1.5012
Epoch: 3/10... Step: 10700... Loss: 1.2506... Val Loss: 1.4962
Epoch: 3/10... Step: 10710... Loss: 1.3465... Val Loss: 1.4923
Epoch: 3/10... Step: 10720... Loss: 1.3863... Val Loss: 1.4902
Epoch: 3/10... Step: 10730... Loss: 1.2361... Val Loss: 1.4929
Epoch: 3/10... Step: 10740... Loss: 1.4420... Val Loss: 1.4906
Epoch: 3/10... Step: 10750... Loss: 1.3035... Val Loss: 1.4914
Epoch: 3/10... Step: 10760... Loss: 1.3826... Val Loss: 1.4925
Epoch: 3/10... Step: 10770... Loss: 1.2844... Val Loss: 1.4880
Epoch: 3/10... Step: 10780... Loss: 1.2717... Val Loss: 1.4954
Epoch: 3/10... Step: 10790... Loss: 1.4087... Val Loss: 1.4931
Epoch: 3/10... Step: 10800... Loss: 1.4739... Val Loss:

Epoch: 3/10... Step: 11960... Loss: 1.4557... Val Loss: 1.4752
Epoch: 3/10... Step: 11970... Loss: 1.3615... Val Loss: 1.4746
Epoch: 3/10... Step: 11980... Loss: 1.2645... Val Loss: 1.4717
Epoch: 3/10... Step: 11990... Loss: 1.3089... Val Loss: 1.4734
Epoch: 3/10... Step: 12000... Loss: 1.3979... Val Loss: 1.4766
Epoch: 3/10... Step: 12010... Loss: 1.3381... Val Loss: 1.4756
Epoch: 3/10... Step: 12020... Loss: 1.4438... Val Loss: 1.4772
Epoch: 3/10... Step: 12030... Loss: 1.3403... Val Loss: 1.4749
Epoch: 3/10... Step: 12040... Loss: 1.3404... Val Loss: 1.4784
Epoch: 3/10... Step: 12050... Loss: 1.3137... Val Loss: 1.4766
Epoch: 3/10... Step: 12060... Loss: 1.4472... Val Loss: 1.4750
Epoch: 3/10... Step: 12070... Loss: 1.2819... Val Loss: 1.4753
Epoch: 3/10... Step: 12080... Loss: 1.3145... Val Loss: 1.4738
Epoch: 3/10... Step: 12090... Loss: 1.2979... Val Loss: 1.4743
Epoch: 3/10... Step: 12100... Loss: 1.3098... Val Loss: 1.4694
Epoch: 3/10... Step: 12110... Loss: 1.3799... Val Loss:

Epoch: 3/10... Step: 13270... Loss: 1.3177... Val Loss: 1.4665
Epoch: 3/10... Step: 13280... Loss: 1.3116... Val Loss: 1.4628
Epoch: 3/10... Step: 13290... Loss: 1.3507... Val Loss: 1.4602
Epoch: 3/10... Step: 13300... Loss: 1.3186... Val Loss: 1.4657
Epoch: 3/10... Step: 13310... Loss: 1.3486... Val Loss: 1.4646
Epoch: 3/10... Step: 13320... Loss: 1.1759... Val Loss: 1.4652
Epoch: 3/10... Step: 13330... Loss: 1.2731... Val Loss: 1.4658
Epoch: 3/10... Step: 13340... Loss: 1.2693... Val Loss: 1.4694
Epoch: 3/10... Step: 13350... Loss: 1.3597... Val Loss: 1.4601
Epoch: 3/10... Step: 13360... Loss: 1.3215... Val Loss: 1.4614
Epoch: 3/10... Step: 13370... Loss: 1.4544... Val Loss: 1.4611
Epoch: 3/10... Step: 13380... Loss: 1.1847... Val Loss: 1.4645
Epoch: 3/10... Step: 13390... Loss: 1.4639... Val Loss: 1.4585
Epoch: 4/10... Step: 13400... Loss: 1.2330... Val Loss: 1.4624
Epoch: 4/10... Step: 13410... Loss: 1.2604... Val Loss: 1.4583
Epoch: 4/10... Step: 13420... Loss: 1.3256... Val Loss:

Epoch: 4/10... Step: 14580... Loss: 1.3629... Val Loss: 1.4511
Epoch: 4/10... Step: 14590... Loss: 1.4944... Val Loss: 1.4493
Epoch: 4/10... Step: 14600... Loss: 1.3878... Val Loss: 1.4485
Epoch: 4/10... Step: 14610... Loss: 1.1619... Val Loss: 1.4490
Epoch: 4/10... Step: 14620... Loss: 1.3311... Val Loss: 1.4511
Epoch: 4/10... Step: 14630... Loss: 1.1662... Val Loss: 1.4519
Epoch: 4/10... Step: 14640... Loss: 1.2565... Val Loss: 1.4527
Epoch: 4/10... Step: 14650... Loss: 1.2326... Val Loss: 1.4514
Epoch: 4/10... Step: 14660... Loss: 1.3509... Val Loss: 1.4506
Epoch: 4/10... Step: 14670... Loss: 1.3802... Val Loss: 1.4481
Epoch: 4/10... Step: 14680... Loss: 1.2344... Val Loss: 1.4498
Epoch: 4/10... Step: 14690... Loss: 1.2894... Val Loss: 1.4472
Epoch: 4/10... Step: 14700... Loss: 1.2240... Val Loss: 1.4482
Epoch: 4/10... Step: 14710... Loss: 1.1600... Val Loss: 1.4501
Epoch: 4/10... Step: 14720... Loss: 1.4106... Val Loss: 1.4549
Epoch: 4/10... Step: 14730... Loss: 1.3101... Val Loss:

Epoch: 4/10... Step: 15890... Loss: 1.3012... Val Loss: 1.4365
Epoch: 4/10... Step: 15900... Loss: 1.2309... Val Loss: 1.4372
Epoch: 4/10... Step: 15910... Loss: 1.1558... Val Loss: 1.4383
Epoch: 4/10... Step: 15920... Loss: 1.3384... Val Loss: 1.4387
Epoch: 4/10... Step: 15930... Loss: 1.2242... Val Loss: 1.4416
Epoch: 4/10... Step: 15940... Loss: 1.3161... Val Loss: 1.4405
Epoch: 4/10... Step: 15950... Loss: 1.4004... Val Loss: 1.4399
Epoch: 4/10... Step: 15960... Loss: 1.3417... Val Loss: 1.4384
Epoch: 4/10... Step: 15970... Loss: 1.2458... Val Loss: 1.4383
Epoch: 4/10... Step: 15980... Loss: 1.2619... Val Loss: 1.4411
Epoch: 4/10... Step: 15990... Loss: 1.3330... Val Loss: 1.4470
Epoch: 4/10... Step: 16000... Loss: 1.2380... Val Loss: 1.4445
Epoch: 4/10... Step: 16010... Loss: 1.2768... Val Loss: 1.4443
Epoch: 4/10... Step: 16020... Loss: 1.2983... Val Loss: 1.4454
Epoch: 4/10... Step: 16030... Loss: 1.2746... Val Loss: 1.4405
Epoch: 4/10... Step: 16040... Loss: 1.4553... Val Loss:

Epoch: 4/10... Step: 17200... Loss: 1.2615... Val Loss: 1.4299
Epoch: 4/10... Step: 17210... Loss: 1.2144... Val Loss: 1.4312
Epoch: 4/10... Step: 17220... Loss: 1.3810... Val Loss: 1.4261
Epoch: 4/10... Step: 17230... Loss: 1.2459... Val Loss: 1.4259
Epoch: 4/10... Step: 17240... Loss: 1.3884... Val Loss: 1.4292
Epoch: 4/10... Step: 17250... Loss: 1.3931... Val Loss: 1.4291
Epoch: 4/10... Step: 17260... Loss: 1.4265... Val Loss: 1.4298
Epoch: 4/10... Step: 17270... Loss: 1.3493... Val Loss: 1.4286
Epoch: 4/10... Step: 17280... Loss: 1.2078... Val Loss: 1.4302
Epoch: 4/10... Step: 17290... Loss: 1.3423... Val Loss: 1.4301
Epoch: 4/10... Step: 17300... Loss: 1.3362... Val Loss: 1.4313
Epoch: 4/10... Step: 17310... Loss: 1.3941... Val Loss: 1.4328
Epoch: 4/10... Step: 17320... Loss: 1.2152... Val Loss: 1.4333
Epoch: 4/10... Step: 17330... Loss: 1.1514... Val Loss: 1.4304
Epoch: 4/10... Step: 17340... Loss: 1.3484... Val Loss: 1.4307
Epoch: 4/10... Step: 17350... Loss: 1.2023... Val Loss:

Epoch: 5/10... Step: 18510... Loss: 1.1255... Val Loss: 1.4259
Epoch: 5/10... Step: 18520... Loss: 1.1687... Val Loss: 1.4234
Epoch: 5/10... Step: 18530... Loss: 1.1668... Val Loss: 1.4264
Epoch: 5/10... Step: 18540... Loss: 1.4124... Val Loss: 1.4265
Epoch: 5/10... Step: 18550... Loss: 1.3887... Val Loss: 1.4267
Epoch: 5/10... Step: 18560... Loss: 1.2805... Val Loss: 1.4273
Epoch: 5/10... Step: 18570... Loss: 1.2402... Val Loss: 1.4234
Epoch: 5/10... Step: 18580... Loss: 1.3396... Val Loss: 1.4223
Epoch: 5/10... Step: 18590... Loss: 1.3558... Val Loss: 1.4213
Epoch: 5/10... Step: 18600... Loss: 1.4009... Val Loss: 1.4200
Epoch: 5/10... Step: 18610... Loss: 1.1206... Val Loss: 1.4204
Epoch: 5/10... Step: 18620... Loss: 1.2396... Val Loss: 1.4179
Epoch: 5/10... Step: 18630... Loss: 1.3330... Val Loss: 1.4181
Epoch: 5/10... Step: 18640... Loss: 1.2833... Val Loss: 1.4247
Epoch: 5/10... Step: 18650... Loss: 1.2162... Val Loss: 1.4205
Epoch: 5/10... Step: 18660... Loss: 1.1382... Val Loss:

Epoch: 5/10... Step: 19820... Loss: 1.2495... Val Loss: 1.4261
Epoch: 5/10... Step: 19830... Loss: 1.2283... Val Loss: 1.4232
Epoch: 5/10... Step: 19840... Loss: 1.2625... Val Loss: 1.4223
Epoch: 5/10... Step: 19850... Loss: 1.3077... Val Loss: 1.4230
Epoch: 5/10... Step: 19860... Loss: 1.3499... Val Loss: 1.4241
Epoch: 5/10... Step: 19870... Loss: 1.2274... Val Loss: 1.4262
Epoch: 5/10... Step: 19880... Loss: 1.1370... Val Loss: 1.4251
Epoch: 5/10... Step: 19890... Loss: 1.2953... Val Loss: 1.4241
Epoch: 5/10... Step: 19900... Loss: 1.1887... Val Loss: 1.4256
Epoch: 5/10... Step: 19910... Loss: 1.2979... Val Loss: 1.4231
Epoch: 5/10... Step: 19920... Loss: 1.1557... Val Loss: 1.4208
Epoch: 5/10... Step: 19930... Loss: 1.4429... Val Loss: 1.4297
Epoch: 5/10... Step: 19940... Loss: 1.2910... Val Loss: 1.4283
Epoch: 5/10... Step: 19950... Loss: 1.1249... Val Loss: 1.4284
Epoch: 5/10... Step: 19960... Loss: 1.2748... Val Loss: 1.4217
Epoch: 5/10... Step: 19970... Loss: 1.2111... Val Loss:

Epoch: 5/10... Step: 21130... Loss: 1.2499... Val Loss: 1.4178
Epoch: 5/10... Step: 21140... Loss: 1.2566... Val Loss: 1.4115
Epoch: 5/10... Step: 21150... Loss: 1.2254... Val Loss: 1.4113
Epoch: 5/10... Step: 21160... Loss: 1.1719... Val Loss: 1.4141
Epoch: 5/10... Step: 21170... Loss: 1.4302... Val Loss: 1.4133
Epoch: 5/10... Step: 21180... Loss: 1.1104... Val Loss: 1.4105
Epoch: 5/10... Step: 21190... Loss: 1.2974... Val Loss: 1.4102
Epoch: 5/10... Step: 21200... Loss: 1.2198... Val Loss: 1.4100
Epoch: 5/10... Step: 21210... Loss: 1.3702... Val Loss: 1.4103
Epoch: 5/10... Step: 21220... Loss: 1.3740... Val Loss: 1.4105
Epoch: 5/10... Step: 21230... Loss: 1.3914... Val Loss: 1.4123
Epoch: 5/10... Step: 21240... Loss: 1.3212... Val Loss: 1.4108
Epoch: 5/10... Step: 21250... Loss: 1.3208... Val Loss: 1.4080
Epoch: 5/10... Step: 21260... Loss: 1.3179... Val Loss: 1.4119
Epoch: 5/10... Step: 21270... Loss: 1.3718... Val Loss: 1.4169
Epoch: 5/10... Step: 21280... Loss: 1.2540... Val Loss:

Epoch: 6/10... Step: 22440... Loss: 1.2124... Val Loss: 1.4085
Epoch: 6/10... Step: 22450... Loss: 1.4247... Val Loss: 1.4099
Epoch: 6/10... Step: 22460... Loss: 1.3256... Val Loss: 1.4146
Epoch: 6/10... Step: 22470... Loss: 1.2988... Val Loss: 1.4143
Epoch: 6/10... Step: 22480... Loss: 1.2677... Val Loss: 1.4143
Epoch: 6/10... Step: 22490... Loss: 1.3540... Val Loss: 1.4139
Epoch: 6/10... Step: 22500... Loss: 1.2712... Val Loss: 1.4134
Epoch: 6/10... Step: 22510... Loss: 1.3259... Val Loss: 1.4121
Epoch: 6/10... Step: 22520... Loss: 1.2237... Val Loss: 1.4095
Epoch: 6/10... Step: 22530... Loss: 1.1064... Val Loss: 1.4102
Epoch: 6/10... Step: 22540... Loss: 1.3599... Val Loss: 1.4114
Epoch: 6/10... Step: 22550... Loss: 1.1720... Val Loss: 1.4117
Epoch: 6/10... Step: 22560... Loss: 1.3041... Val Loss: 1.4118
Epoch: 6/10... Step: 22570... Loss: 1.2302... Val Loss: 1.4122
Epoch: 6/10... Step: 22580... Loss: 1.3103... Val Loss: 1.4124
Epoch: 6/10... Step: 22590... Loss: 1.2492... Val Loss:

Epoch: 6/10... Step: 23750... Loss: 1.1266... Val Loss: 1.4008
Epoch: 6/10... Step: 23760... Loss: 1.3386... Val Loss: 1.4047
Epoch: 6/10... Step: 23770... Loss: 1.2530... Val Loss: 1.4103
Epoch: 6/10... Step: 23780... Loss: 1.3821... Val Loss: 1.4072
Epoch: 6/10... Step: 23790... Loss: 1.2614... Val Loss: 1.4074
Epoch: 6/10... Step: 23800... Loss: 1.1983... Val Loss: 1.4052
Epoch: 6/10... Step: 23810... Loss: 1.1775... Val Loss: 1.4055
Epoch: 6/10... Step: 23820... Loss: 1.2777... Val Loss: 1.4027
Epoch: 6/10... Step: 23830... Loss: 1.1229... Val Loss: 1.4015
Epoch: 6/10... Step: 23840... Loss: 1.3027... Val Loss: 1.4016
Epoch: 6/10... Step: 23850... Loss: 1.3320... Val Loss: 1.4025
Epoch: 6/10... Step: 23860... Loss: 1.1352... Val Loss: 1.3991
Epoch: 6/10... Step: 23870... Loss: 1.2835... Val Loss: 1.4022
Epoch: 6/10... Step: 23880... Loss: 1.2494... Val Loss: 1.4069
Epoch: 6/10... Step: 23890... Loss: 1.2748... Val Loss: 1.4060
Epoch: 6/10... Step: 23900... Loss: 1.1396... Val Loss:

Epoch: 6/10... Step: 25060... Loss: 1.2669... Val Loss: 1.4015
Epoch: 6/10... Step: 25070... Loss: 1.1886... Val Loss: 1.3983
Epoch: 6/10... Step: 25080... Loss: 1.2494... Val Loss: 1.4000
Epoch: 6/10... Step: 25090... Loss: 1.2909... Val Loss: 1.3994
Epoch: 6/10... Step: 25100... Loss: 1.2998... Val Loss: 1.3947
Epoch: 6/10... Step: 25110... Loss: 1.2066... Val Loss: 1.3937
Epoch: 6/10... Step: 25120... Loss: 1.0821... Val Loss: 1.3944
Epoch: 6/10... Step: 25130... Loss: 1.2360... Val Loss: 1.3976
Epoch: 6/10... Step: 25140... Loss: 1.2057... Val Loss: 1.3952
Epoch: 6/10... Step: 25150... Loss: 1.4209... Val Loss: 1.3980
Epoch: 6/10... Step: 25160... Loss: 1.4448... Val Loss: 1.3951
Epoch: 6/10... Step: 25170... Loss: 1.2211... Val Loss: 1.3975
Epoch: 6/10... Step: 25180... Loss: 1.2092... Val Loss: 1.3972
Epoch: 6/10... Step: 25190... Loss: 1.2463... Val Loss: 1.3985
Epoch: 6/10... Step: 25200... Loss: 1.3848... Val Loss: 1.3993
Epoch: 6/10... Step: 25210... Loss: 1.3157... Val Loss:

Epoch: 6/10... Step: 26370... Loss: 1.2309... Val Loss: 1.3977
Epoch: 6/10... Step: 26380... Loss: 1.2132... Val Loss: 1.3990
Epoch: 6/10... Step: 26390... Loss: 1.1133... Val Loss: 1.4027
Epoch: 6/10... Step: 26400... Loss: 1.2963... Val Loss: 1.3973
Epoch: 6/10... Step: 26410... Loss: 1.1224... Val Loss: 1.3941
Epoch: 6/10... Step: 26420... Loss: 1.2073... Val Loss: 1.3979
Epoch: 6/10... Step: 26430... Loss: 1.1062... Val Loss: 1.3983
Epoch: 6/10... Step: 26440... Loss: 1.1312... Val Loss: 1.3983
Epoch: 6/10... Step: 26450... Loss: 1.2270... Val Loss: 1.4011
Epoch: 6/10... Step: 26460... Loss: 1.2318... Val Loss: 1.4022
Epoch: 6/10... Step: 26470... Loss: 1.4039... Val Loss: 1.3969
Epoch: 6/10... Step: 26480... Loss: 1.2101... Val Loss: 1.3963
Epoch: 6/10... Step: 26490... Loss: 1.2128... Val Loss: 1.3971
Epoch: 6/10... Step: 26500... Loss: 1.4023... Val Loss: 1.3992
Epoch: 6/10... Step: 26510... Loss: 1.2647... Val Loss: 1.3960
Epoch: 6/10... Step: 26520... Loss: 1.1905... Val Loss:

Epoch: 7/10... Step: 27680... Loss: 1.1189... Val Loss: 1.3966
Epoch: 7/10... Step: 27690... Loss: 1.3394... Val Loss: 1.3969
Epoch: 7/10... Step: 27700... Loss: 1.1700... Val Loss: 1.3914
Epoch: 7/10... Step: 27710... Loss: 1.2693... Val Loss: 1.3930
Epoch: 7/10... Step: 27720... Loss: 1.1107... Val Loss: 1.3970
Epoch: 7/10... Step: 27730... Loss: 1.2641... Val Loss: 1.3932
Epoch: 7/10... Step: 27740... Loss: 1.2977... Val Loss: 1.3937
Epoch: 7/10... Step: 27750... Loss: 1.0267... Val Loss: 1.3933
Epoch: 7/10... Step: 27760... Loss: 1.1039... Val Loss: 1.3936
Epoch: 7/10... Step: 27770... Loss: 1.0923... Val Loss: 1.3991
Epoch: 7/10... Step: 27780... Loss: 1.2280... Val Loss: 1.3998
Epoch: 7/10... Step: 27790... Loss: 1.2313... Val Loss: 1.3935
Epoch: 7/10... Step: 27800... Loss: 1.0649... Val Loss: 1.3959
Epoch: 7/10... Step: 27810... Loss: 1.0724... Val Loss: 1.3984
Epoch: 7/10... Step: 27820... Loss: 1.2574... Val Loss: 1.3952
Epoch: 7/10... Step: 27830... Loss: 1.1178... Val Loss:

Epoch: 7/10... Step: 28990... Loss: 1.2570... Val Loss: 1.3991
Epoch: 7/10... Step: 29000... Loss: 1.2355... Val Loss: 1.3973
Epoch: 7/10... Step: 29010... Loss: 1.1932... Val Loss: 1.3962
Epoch: 7/10... Step: 29020... Loss: 1.1620... Val Loss: 1.3969
Epoch: 7/10... Step: 29030... Loss: 1.2798... Val Loss: 1.3985
Epoch: 7/10... Step: 29040... Loss: 1.1129... Val Loss: 1.3967
Epoch: 7/10... Step: 29050... Loss: 1.2908... Val Loss: 1.3979
Epoch: 7/10... Step: 29060... Loss: 1.3339... Val Loss: 1.3977
Epoch: 7/10... Step: 29070... Loss: 1.0685... Val Loss: 1.3942
Epoch: 7/10... Step: 29080... Loss: 1.1945... Val Loss: 1.3962
Epoch: 7/10... Step: 29090... Loss: 1.3200... Val Loss: 1.3970
Epoch: 7/10... Step: 29100... Loss: 1.1212... Val Loss: 1.3938
Epoch: 7/10... Step: 29110... Loss: 1.2946... Val Loss: 1.3954
Epoch: 7/10... Step: 29120... Loss: 1.3556... Val Loss: 1.3926
Epoch: 7/10... Step: 29130... Loss: 1.2245... Val Loss: 1.3942
Epoch: 7/10... Step: 29140... Loss: 1.1860... Val Loss:

Epoch: 7/10... Step: 30300... Loss: 1.0909... Val Loss: 1.3888
Epoch: 7/10... Step: 30310... Loss: 1.1891... Val Loss: 1.3872
Epoch: 7/10... Step: 30320... Loss: 1.2307... Val Loss: 1.3875
Epoch: 7/10... Step: 30330... Loss: 1.1283... Val Loss: 1.3846
Epoch: 7/10... Step: 30340... Loss: 1.3804... Val Loss: 1.3837
Epoch: 7/10... Step: 30350... Loss: 1.1233... Val Loss: 1.3882
Epoch: 7/10... Step: 30360... Loss: 1.2611... Val Loss: 1.3890
Epoch: 7/10... Step: 30370... Loss: 1.1405... Val Loss: 1.3841
Epoch: 7/10... Step: 30380... Loss: 1.0295... Val Loss: 1.3828
Epoch: 7/10... Step: 30390... Loss: 1.4386... Val Loss: 1.3850
Epoch: 7/10... Step: 30400... Loss: 1.1899... Val Loss: 1.3898
Epoch: 7/10... Step: 30410... Loss: 1.3053... Val Loss: 1.3889
Epoch: 7/10... Step: 30420... Loss: 1.3677... Val Loss: 1.3891
Epoch: 7/10... Step: 30430... Loss: 1.3768... Val Loss: 1.3878
Epoch: 7/10... Step: 30440... Loss: 1.2233... Val Loss: 1.3886
Epoch: 7/10... Step: 30450... Loss: 1.2416... Val Loss:

Epoch: 8/10... Step: 31610... Loss: 1.2176... Val Loss: 1.3818
Epoch: 8/10... Step: 31620... Loss: 1.2251... Val Loss: 1.3834
Epoch: 8/10... Step: 31630... Loss: 1.1448... Val Loss: 1.3820
Epoch: 8/10... Step: 31640... Loss: 1.2826... Val Loss: 1.3834
Epoch: 8/10... Step: 31650... Loss: 1.3189... Val Loss: 1.3899
Epoch: 8/10... Step: 31660... Loss: 1.1714... Val Loss: 1.3885
Epoch: 8/10... Step: 31670... Loss: 1.1567... Val Loss: 1.3911
Epoch: 8/10... Step: 31680... Loss: 1.2655... Val Loss: 1.3891
Epoch: 8/10... Step: 31690... Loss: 1.3242... Val Loss: 1.3868
Epoch: 8/10... Step: 31700... Loss: 1.2772... Val Loss: 1.3864
Epoch: 8/10... Step: 31710... Loss: 1.2073... Val Loss: 1.3819
Epoch: 8/10... Step: 31720... Loss: 1.3457... Val Loss: 1.3803
Epoch: 8/10... Step: 31730... Loss: 1.1673... Val Loss: 1.3818
Epoch: 8/10... Step: 31740... Loss: 1.1799... Val Loss: 1.3862
Epoch: 8/10... Step: 31750... Loss: 1.2731... Val Loss: 1.3837
Epoch: 8/10... Step: 31760... Loss: 1.2761... Val Loss:

Epoch: 8/10... Step: 32920... Loss: 1.2809... Val Loss: 1.3830
Epoch: 8/10... Step: 32930... Loss: 1.1613... Val Loss: 1.3843
Epoch: 8/10... Step: 32940... Loss: 1.2467... Val Loss: 1.3861
Epoch: 8/10... Step: 32950... Loss: 1.3187... Val Loss: 1.3859
Epoch: 8/10... Step: 32960... Loss: 1.1012... Val Loss: 1.3879
Epoch: 8/10... Step: 32970... Loss: 1.2808... Val Loss: 1.3850
Epoch: 8/10... Step: 32980... Loss: 1.1819... Val Loss: 1.3847
Epoch: 8/10... Step: 32990... Loss: 1.2304... Val Loss: 1.3894
Epoch: 8/10... Step: 33000... Loss: 1.1165... Val Loss: 1.3887
Epoch: 8/10... Step: 33010... Loss: 1.2059... Val Loss: 1.3906
Epoch: 8/10... Step: 33020... Loss: 1.2830... Val Loss: 1.3900
Epoch: 8/10... Step: 33030... Loss: 1.1049... Val Loss: 1.3900
Epoch: 8/10... Step: 33040... Loss: 1.2216... Val Loss: 1.3875
Epoch: 8/10... Step: 33050... Loss: 1.1790... Val Loss: 1.3889
Epoch: 8/10... Step: 33060... Loss: 1.1152... Val Loss: 1.3907
Epoch: 8/10... Step: 33070... Loss: 1.2734... Val Loss:

Epoch: 8/10... Step: 34230... Loss: 1.1234... Val Loss: 1.3828
Epoch: 8/10... Step: 34240... Loss: 1.0990... Val Loss: 1.3815
Epoch: 8/10... Step: 34250... Loss: 1.2103... Val Loss: 1.3816
Epoch: 8/10... Step: 34260... Loss: 1.2158... Val Loss: 1.3818
Epoch: 8/10... Step: 34270... Loss: 1.0903... Val Loss: 1.3823
Epoch: 8/10... Step: 34280... Loss: 1.0814... Val Loss: 1.3844
Epoch: 8/10... Step: 34290... Loss: 1.2861... Val Loss: 1.3818
Epoch: 8/10... Step: 34300... Loss: 1.2562... Val Loss: 1.3808
Epoch: 8/10... Step: 34310... Loss: 1.1132... Val Loss: 1.3819
Epoch: 8/10... Step: 34320... Loss: 1.1776... Val Loss: 1.3845
Epoch: 8/10... Step: 34330... Loss: 1.1851... Val Loss: 1.3855
Epoch: 8/10... Step: 34340... Loss: 1.1869... Val Loss: 1.3845
Epoch: 8/10... Step: 34350... Loss: 1.3154... Val Loss: 1.3864
Epoch: 8/10... Step: 34360... Loss: 1.2078... Val Loss: 1.3860
Epoch: 8/10... Step: 34370... Loss: 1.2308... Val Loss: 1.3872
Epoch: 8/10... Step: 34380... Loss: 1.1897... Val Loss:

Epoch: 8/10... Step: 35540... Loss: 1.5362... Val Loss: 1.3791
Epoch: 8/10... Step: 35550... Loss: 1.3710... Val Loss: 1.3798
Epoch: 8/10... Step: 35560... Loss: 1.2413... Val Loss: 1.3800
Epoch: 8/10... Step: 35570... Loss: 1.2516... Val Loss: 1.3827
Epoch: 8/10... Step: 35580... Loss: 1.2233... Val Loss: 1.3840
Epoch: 8/10... Step: 35590... Loss: 1.0562... Val Loss: 1.3815
Epoch: 8/10... Step: 35600... Loss: 1.1438... Val Loss: 1.3807
Epoch: 8/10... Step: 35610... Loss: 1.2154... Val Loss: 1.3782
Epoch: 8/10... Step: 35620... Loss: 1.1887... Val Loss: 1.3770
Epoch: 8/10... Step: 35630... Loss: 1.2031... Val Loss: 1.3833
Epoch: 8/10... Step: 35640... Loss: 1.1735... Val Loss: 1.3861
Epoch: 8/10... Step: 35650... Loss: 1.1314... Val Loss: 1.3811
Epoch: 8/10... Step: 35660... Loss: 1.1559... Val Loss: 1.3822
Epoch: 8/10... Step: 35670... Loss: 1.1334... Val Loss: 1.3839
Epoch: 8/10... Step: 35680... Loss: 1.2844... Val Loss: 1.3811
Epoch: 8/10... Step: 35690... Loss: 1.2425... Val Loss:

Epoch: 9/10... Step: 36850... Loss: 1.1265... Val Loss: 1.3748
Epoch: 9/10... Step: 36860... Loss: 1.2341... Val Loss: 1.3796
Epoch: 9/10... Step: 36870... Loss: 1.0910... Val Loss: 1.3801
Epoch: 9/10... Step: 36880... Loss: 1.1975... Val Loss: 1.3772
Epoch: 9/10... Step: 36890... Loss: 1.1667... Val Loss: 1.3755
Epoch: 9/10... Step: 36900... Loss: 1.3995... Val Loss: 1.3777
Epoch: 9/10... Step: 36910... Loss: 1.2441... Val Loss: 1.3779
Epoch: 9/10... Step: 36920... Loss: 1.3681... Val Loss: 1.3772
Epoch: 9/10... Step: 36930... Loss: 1.2944... Val Loss: 1.3739
Epoch: 9/10... Step: 36940... Loss: 1.0608... Val Loss: 1.3735
Epoch: 9/10... Step: 36950... Loss: 1.1820... Val Loss: 1.3779
Epoch: 9/10... Step: 36960... Loss: 1.0729... Val Loss: 1.3799
Epoch: 9/10... Step: 36970... Loss: 1.1474... Val Loss: 1.3791
Epoch: 9/10... Step: 36980... Loss: 1.1098... Val Loss: 1.3798
Epoch: 9/10... Step: 36990... Loss: 1.2088... Val Loss: 1.3811
Epoch: 9/10... Step: 37000... Loss: 1.2253... Val Loss:

Epoch: 9/10... Step: 38160... Loss: 1.3083... Val Loss: 1.3772
Epoch: 9/10... Step: 38170... Loss: 1.2084... Val Loss: 1.3771
Epoch: 9/10... Step: 38180... Loss: 0.9922... Val Loss: 1.3756
Epoch: 9/10... Step: 38190... Loss: 1.2906... Val Loss: 1.3763
Epoch: 9/10... Step: 38200... Loss: 1.2804... Val Loss: 1.3740
Epoch: 9/10... Step: 38210... Loss: 1.1311... Val Loss: 1.3737
Epoch: 9/10... Step: 38220... Loss: 1.2024... Val Loss: 1.3722
Epoch: 9/10... Step: 38230... Loss: 1.1131... Val Loss: 1.3704
Epoch: 9/10... Step: 38240... Loss: 1.0886... Val Loss: 1.3716
Epoch: 9/10... Step: 38250... Loss: 1.2096... Val Loss: 1.3728
Epoch: 9/10... Step: 38260... Loss: 1.1493... Val Loss: 1.3731
Epoch: 9/10... Step: 38270... Loss: 1.2446... Val Loss: 1.3732
Epoch: 9/10... Step: 38280... Loss: 1.3201... Val Loss: 1.3730
Epoch: 9/10... Step: 38290... Loss: 1.2255... Val Loss: 1.3711
Epoch: 9/10... Step: 38300... Loss: 1.1186... Val Loss: 1.3732
Epoch: 9/10... Step: 38310... Loss: 1.2242... Val Loss:

Epoch: 9/10... Step: 39470... Loss: 1.2834... Val Loss: 1.3674
Epoch: 9/10... Step: 39480... Loss: 1.1818... Val Loss: 1.3675
Epoch: 9/10... Step: 39490... Loss: 1.1960... Val Loss: 1.3727
Epoch: 9/10... Step: 39500... Loss: 1.1317... Val Loss: 1.3706
Epoch: 9/10... Step: 39510... Loss: 1.1297... Val Loss: 1.3699
Epoch: 9/10... Step: 39520... Loss: 1.3505... Val Loss: 1.3704
Epoch: 9/10... Step: 39530... Loss: 1.1919... Val Loss: 1.3669
Epoch: 9/10... Step: 39540... Loss: 1.1398... Val Loss: 1.3683
Epoch: 9/10... Step: 39550... Loss: 1.2098... Val Loss: 1.3675
Epoch: 9/10... Step: 39560... Loss: 1.1794... Val Loss: 1.3679
Epoch: 9/10... Step: 39570... Loss: 1.2848... Val Loss: 1.3700
Epoch: 9/10... Step: 39580... Loss: 1.3103... Val Loss: 1.3705
Epoch: 9/10... Step: 39590... Loss: 1.2908... Val Loss: 1.3716
Epoch: 9/10... Step: 39600... Loss: 1.2444... Val Loss: 1.3723
Epoch: 9/10... Step: 39610... Loss: 1.1594... Val Loss: 1.3720
Epoch: 9/10... Step: 39620... Loss: 1.2178... Val Loss:

Epoch: 10/10... Step: 40770... Loss: 1.0892... Val Loss: 1.3725
Epoch: 10/10... Step: 40780... Loss: 1.1951... Val Loss: 1.3739
Epoch: 10/10... Step: 40790... Loss: 1.2928... Val Loss: 1.3730
Epoch: 10/10... Step: 40800... Loss: 0.9271... Val Loss: 1.3732
Epoch: 10/10... Step: 40810... Loss: 1.1759... Val Loss: 1.3696
Epoch: 10/10... Step: 40820... Loss: 1.2934... Val Loss: 1.3706
Epoch: 10/10... Step: 40830... Loss: 1.0869... Val Loss: 1.3730
Epoch: 10/10... Step: 40840... Loss: 1.0790... Val Loss: 1.3730
Epoch: 10/10... Step: 40850... Loss: 1.0768... Val Loss: 1.3723
Epoch: 10/10... Step: 40860... Loss: 1.0648... Val Loss: 1.3732
Epoch: 10/10... Step: 40870... Loss: 1.3251... Val Loss: 1.3736
Epoch: 10/10... Step: 40880... Loss: 1.2823... Val Loss: 1.3715
Epoch: 10/10... Step: 40890... Loss: 1.1669... Val Loss: 1.3709
Epoch: 10/10... Step: 40900... Loss: 1.1398... Val Loss: 1.3674
Epoch: 10/10... Step: 40910... Loss: 1.2314... Val Loss: 1.3698
Epoch: 10/10... Step: 40920... Loss: 1.2

Epoch: 10/10... Step: 42060... Loss: 1.1826... Val Loss: 1.3749
Epoch: 10/10... Step: 42070... Loss: 1.1882... Val Loss: 1.3728
Epoch: 10/10... Step: 42080... Loss: 1.3531... Val Loss: 1.3717
Epoch: 10/10... Step: 42090... Loss: 1.1269... Val Loss: 1.3712
Epoch: 10/10... Step: 42100... Loss: 1.2533... Val Loss: 1.3720
Epoch: 10/10... Step: 42110... Loss: 1.0609... Val Loss: 1.3730
Epoch: 10/10... Step: 42120... Loss: 1.1949... Val Loss: 1.3733
Epoch: 10/10... Step: 42130... Loss: 1.2685... Val Loss: 1.3708
Epoch: 10/10... Step: 42140... Loss: 1.1967... Val Loss: 1.3705
Epoch: 10/10... Step: 42150... Loss: 1.1670... Val Loss: 1.3714
Epoch: 10/10... Step: 42160... Loss: 1.1590... Val Loss: 1.3717
Epoch: 10/10... Step: 42170... Loss: 1.1619... Val Loss: 1.3704
Epoch: 10/10... Step: 42180... Loss: 1.2233... Val Loss: 1.3731
Epoch: 10/10... Step: 42190... Loss: 1.2688... Val Loss: 1.3728
Epoch: 10/10... Step: 42200... Loss: 1.1336... Val Loss: 1.3755
Epoch: 10/10... Step: 42210... Loss: 1.0

Epoch: 10/10... Step: 43350... Loss: 1.0014... Val Loss: 1.3674
Epoch: 10/10... Step: 43360... Loss: 1.1091... Val Loss: 1.3678
Epoch: 10/10... Step: 43370... Loss: 1.2819... Val Loss: 1.3657
Epoch: 10/10... Step: 43380... Loss: 1.1374... Val Loss: 1.3687
Epoch: 10/10... Step: 43390... Loss: 1.2747... Val Loss: 1.3694
Epoch: 10/10... Step: 43400... Loss: 1.1845... Val Loss: 1.3679
Epoch: 10/10... Step: 43410... Loss: 1.1329... Val Loss: 1.3686
Epoch: 10/10... Step: 43420... Loss: 1.1393... Val Loss: 1.3704
Epoch: 10/10... Step: 43430... Loss: 1.2317... Val Loss: 1.3694
Epoch: 10/10... Step: 43440... Loss: 1.2420... Val Loss: 1.3720
Epoch: 10/10... Step: 43450... Loss: 1.2316... Val Loss: 1.3735
Epoch: 10/10... Step: 43460... Loss: 1.1469... Val Loss: 1.3761
Epoch: 10/10... Step: 43470... Loss: 1.1923... Val Loss: 1.3709
Epoch: 10/10... Step: 43480... Loss: 1.1056... Val Loss: 1.3692
Epoch: 10/10... Step: 43490... Loss: 1.0615... Val Loss: 1.3689
Epoch: 10/10... Step: 43500... Loss: 1.3

Epoch: 10/10... Step: 44640... Loss: 1.2595... Val Loss: 1.3682
Epoch: 10/10... Step: 44650... Loss: 1.1903... Val Loss: 1.3705
Epoch: 10/10... Step: 44660... Loss: 1.0999... Val Loss: 1.3703


## Getting the best model

To set your hyperparameters to get the best performance, you'll want to watch the training and validation losses. If your training loss is much lower than the validation loss, you're overfitting. Increase regularization (more dropout) or use a smaller network. If the training and validation losses are close, you're underfitting so you can increase the size of the network.

## Hyperparameters

Here are the hyperparameters for the network.

In defining the model:
* `n_hidden` - The number of units in the hidden layers.
* `n_layers` - Number of hidden LSTM layers to use.

We assume that dropout probability and learning rate will be kept at the default, in this example.

And in training:
* `batch_size` - Number of sequences running through the network in one pass.
* `seq_length` - Number of characters in the sequence the network is trained on. Larger is better typically, the network will learn more long range dependencies. But it takes longer to train. 100 is typically a good number here.
* `lr` - Learning rate for training

Here's some good advice from Andrej Karpathy on training the network. I'm going to copy it in here for your benefit, but also link to [where it originally came from](https://github.com/karpathy/char-rnn#tips-and-tricks).

> ## Tips and Tricks

>### Monitoring Validation Loss vs. Training Loss
>If you're somewhat new to Machine Learning or Neural Networks it can take a bit of expertise to get good models. The most important quantity to keep track of is the difference between your training loss (printed during training) and the validation loss (printed once in a while when the RNN is run on the validation data (by default every 1000 iterations)). In particular:

> - If your training loss is much lower than validation loss then this means the network might be **overfitting**. Solutions to this are to decrease your network size, or to increase dropout. For example you could try dropout of 0.5 and so on.
> - If your training/validation loss are about equal then your model is **underfitting**. Increase the size of your model (either number of layers or the raw number of neurons per layer)

> ### Approximate number of parameters

> The two most important parameters that control the model are `n_hidden` and `n_layers`. I would advise that you always use `n_layers` of either 2/3. The `n_hidden` can be adjusted based on how much data you have. The two important quantities to keep track of here are:

> - The number of parameters in your model. This is printed when you start training.
> - The size of your dataset. 1MB file is approximately 1 million characters.

>These two should be about the same order of magnitude. It's a little tricky to tell. Here are some examples:

> - I have a 100MB dataset and I'm using the default parameter settings (which currently print 150K parameters). My data size is significantly larger (100 mil >> 0.15 mil), so I expect to heavily underfit. I am thinking I can comfortably afford to make `n_hidden` larger.
> - I have a 10MB dataset and running a 10 million parameter model. I'm slightly nervous and I'm carefully monitoring my validation loss. If it's larger than my training loss then I may want to try to increase dropout a bit and see if that helps the validation loss.

> ### Best models strategy

>The winning strategy to obtaining very good models (if you have the compute time) is to always err on making the network larger (as large as you're willing to wait for it to compute) and then try different dropout values (between 0,1). Whatever model has the best validation performance (the loss, written in the checkpoint filename, low is good) is the one you should use in the end.

>It is very common in deep learning to run many different models with many different hyperparameter settings, and in the end take whatever checkpoint gave the best validation performance.

>By the way, the size of your training and validation splits are also parameters. Make sure you have a decent amount of data in your validation set or otherwise the validation performance will be noisy and not very informative.

## Checkpoint

After training, we'll save the model so we can load it again later if we need too. Here I'm saving the parameters needed to create the same architecture, the hidden layer hyperparameters and the text characters.

In [107]:
# change the name, for saving multiple files
model_name = 'rnn_x_epoch.net'

checkpoint = {'n_hidden': net.n_hidden,
              'n_layers': net.n_layers,
              'state_dict': net.state_dict(),
              'tokens': net.chars}

with open(model_name, 'wb') as f:
    torch.save(checkpoint, f)

---
## Making Predictions

Now that the model is trained, we'll want to sample from it and make predictions about next characters! To sample, we pass in a character and have the network predict the next character. Then we take that character, pass it back in, and get another predicted character. Just keep doing this and you'll generate a bunch of text!

### A note on the `predict`  function

The output of our RNN is from a fully-connected layer and it outputs a **distribution of next-character scores**.

> To actually get the next character, we apply a softmax function, which gives us a *probability* distribution that we can then sample to predict the next character.

### Top K sampling

Our predictions come from a categorical probability distribution over all the possible characters. We can make the sample text and make it more reasonable to handle (with less variables) by only considering some $K$ most probable characters. This will prevent the network from giving us completely absurd characters while allowing it to introduce some noise and randomness into the sampled text. Read more about [topk, here](https://pytorch.org/docs/stable/torch.html#torch.topk).


In [108]:
def predict(net, char, h=None, top_k=None):
        ''' Given a character, predict the next character.
            Returns the predicted character and the hidden state.
        '''
        
        # tensor inputs
        x = np.array([[net.char2int[char]]])
        x = one_hot_encode(x, len(net.chars))
        inputs = torch.from_numpy(x)
        
        if(train_on_gpu):
            inputs = inputs.cuda()
        
        # detach hidden state from history
        h = tuple([each.data for each in h])
        # get the output of the model
        out, h = net(inputs, h)

        # get the character probabilities
        p = F.softmax(out, dim=1).data
        if(train_on_gpu):
            p = p.cpu() # move to cpu
        
        # get top characters
        if top_k is None:
            top_ch = np.arange(len(net.chars))
        else:
            p, top_ch = p.topk(top_k)
            top_ch = top_ch.numpy().squeeze()
        
        # select the likely next character with some element of randomness
        p = p.numpy().squeeze()
        char = np.random.choice(top_ch, p=p/p.sum())
        
        # return the encoded value of the predicted char and the hidden state
        return net.int2char[char], h

### Priming and generating text 

Typically you'll want to prime the network so you can build up a hidden state. Otherwise the network will start out generating characters at random. In general the first bunch of characters will be a little rough since it hasn't built up a long history of characters to predict from.

In [109]:
def sample(net, size, prime='The', top_k=None):
        
    if(train_on_gpu):
        net.cuda()
    else:
        net.cpu()
    
    net.eval() # eval mode
    
    # First off, run through the prime characters
    chars = [ch for ch in prime]
    h = net.init_hidden(1)
    for ch in prime:
        char, h = predict(net, ch, h, top_k=top_k)

    chars.append(char)
    
    # Now pass in the previous character and get a new one
    for ii in range(size):
        char, h = predict(net, chars[-1], h, top_k=top_k)
        chars.append(char)

    return ''.join(chars)

In [110]:
print(sample(net, 1000, prime='Anna', top_k=5))

Anna. They settled in the
profit, and
shaking in his chief a study to sit divided her supple by him, and that is any which his brother was simply and down out. After at a shame was the children was the church which had
been seriously at the same part of all to him anywhere so as an institution and drove in
a
long while to surprise him, who had cauted his house as a day was in a smile, the petation was too were all disliked and stopped with his wife, though truth from
the side with a box.

"Those were its better," said that he
was coming on against the
crosing conditions.

"What am I was interested my
position."

"I've taken them."

"I am going to ball
than any of himself women," she said, and she had not had armated that his brother and
since his subject this sense of the contrary of his head and struck himself an insupper in the strange that had seen it and did not care and
take her husband, the better that
this carriages had been cruesting that had been so in the country's face there

## Loading a checkpoint

In [111]:
# Here we have loaded in a model that trained over 20 epochs `rnn_20_epoch.net`
with open('rnn_x_epoch.net', 'rb') as f:
    checkpoint = torch.load(f)
    
loaded = CharRNN(checkpoint['tokens'], n_hidden=checkpoint['n_hidden'], n_layers=checkpoint['n_layers'])
loaded.load_state_dict(checkpoint['state_dict'])

<All keys matched successfully>

In [112]:
# Sample using a loaded model
print(sample(loaded, 2000, top_k=5, prime="And Levin said"))

And Levin said with a significance and most. The study, how society was silk for
mercy, at an old period of their parts, and what had trut to get about this society, had been drinking and
saw that his bridely passed tile a drinking, and the present as he had not answered in the steps of waistcoat--that had
been a life and a silence that had so said to ask him than evidently with the crowd and deceived by
the country were dull at her to comfull. He was crumed. Anything stund all that had been clearly
answered in his children, they were dressed in which he
was staying to her
boudding him. And all they were sitting and the position of his wife, they were awfuls with the burden. All
horses there arown and drank in his habling, which was all to avoid this sort of a brayers that he had been speaking
to him of any fet the candle, and that they
said she could not come. They had not have nothing, and that to strange happiness, but the summer sight to say the children's priest, which he could no